language: node_js
node_js:
  - 10.12.0
cache: yarn

install: 
  - yarn install

script:
  - yarn run test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master